version: "3.4"

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: falconi_frontend
    platform: linux/amd64
    ports:
      - "3001:3000"
    networks:
      - falconi_net
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3000
    restart: on-failure

  api:
    build:
      context: ../backend
    container_name: falconi_api
    platform: linux/amd64
    environment:
      - PORT=3000
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=docker123
      - DB_NAME=FalconiTest
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=FalconiTestRedis123!
      - DOCKER_ENV=true
      - JAEGER_HOST=jaeger
      - JAEGER_PORT=4318
      - OTEL_SDK_ENABLED=true
      - OTEL_SERVICE_NAME=falconi-backend
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
      - OTEL_TRACES_EXPORTER=otlp
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
      jaeger:
        condition: service_started
    networks:
      - falconi_net
  database:
    image: postgres
    platform: linux/amd64
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d FalconiTest -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    container_name: falconi_database
    networks:
      - falconi_net
    environment:
      - POSTGRES_PASSWORD=docker123
      - POSTGRES_DB=FalconiTest
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    platform: linux/amd64
    ports:
      - "6379:6379"
    restart: always
    container_name: falconi_redis
    networks:
      - falconi_net
    command: redis-server --requirepass FalconiTestRedis123!

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4318:4318"
    networks:
      - falconi_net
    restart: always

networks:
  falconi_net:
    driver: bridge

volumes:
  pgdata:
